global using Microsoft.AspNetCore.Mvc;
global using MediatR;
global using Consumer.Application.Core.Emails.Commands;
global using Consumer.Api.Configuration;
global using Consumer.Application.Core;
global using Consumer.Application.Services;
global using Common.Utils;
global using RabbitMq.Helper.Client;
global using RabbitMq.Helper.Interfaces;
